login:
    path: /login
    defaults: { _controller: AdminBundle:Login:login }




admin_homepage.user_add:
    path:     /user/add
    defaults: { _controller: AdminBundle:User:add }

admin_homepage.user_controll:
    path:     /user/add/control
    defaults: { _controller: AdminBundle:User:control }

admin_homepage.news:
    path:     /news
    defaults: { _controller: AdminBundle:News:index }

admin_homepage.news_add:
    path:     /news/add
    defaults: { _controller: AdminBundle:News:add }

admin_homepage.news_edit:
    path:   /news/{id}/edit
    defaults: { _controller: AdminBundle:News:edit }
    requirements:
        id: \d+



admin_homepage.admin:
    path:     /
    defaults: { _controller: AdminBundle:Admin:Index }


admin_homepage.product:
    path:     /product
    defaults: { _controller: AdminBundle:Admin:AdminProduct }

admin_homepage.productlist:
    path:     /productlist/{page}
    defaults: { _controller: AdminBundle:Admin:List , page: 1 }

admin_homepage.productDelete:
    path:     /{id}/productdelete
    defaults: { _controller: AdminBundle:Admin:DeleteProduct }


admin_homepage.product_edit:
    path:     /{id}/edit
    defaults: { _controller: AdminBundle:Admin:EditProduct }




admin_homepage.category:
    path:     /category
    defaults: { _controller: AdminBundle:Category:Category }

admin_homepage.AddCategory:
    path:     /category/add
    defaults: { _controller: AdminBundle:Category:AddCategory }


admin_homepage.categoryproduct:
    path:     category/{id}/product/
    defaults: { _controller: AdminBundle:Admin:CategoryName }

admin_homepage.CategoryDelete:
    path:     /category/{id}/delete
    defaults: { _controller: AdminBundle:Category:DeleteCategory }

admin_homepage.photo_add:
    path:     /product/{idProduct}/photo/add
    defaults: { _controller: AdminBundle:Photo:AddPhoto }


admin_homepage.photo_list:
    path:     /product/{idProduct}/photo
    defaults: { _controller: AdminBundle:Photo:list }

admin_homepage.PhotoDelete:
    path:     /photo/{id}/delete
    defaults: { _controller: AdminBundle:Photo:DeletePhoto }

admin_homepage.ProductPhotoSave:
    path:     /productphoto/{id}/save
    defaults: { _controller: AdminBundle:ProductPhoto:add }

admin_homepage.category_photo_add:
    path:     /category/{idCategory}/photo/add
    defaults: { _controller: AdminBundle:Category:AddPhotoCategory }

admin_homepage.CallBack:
    path:     /callback
    defaults: { _controller: AdminBundle:CAllBack:CAllBack}

admin_homepage.orders_list:
    path:   /orders/{page}
    defaults: { _controller: AdminBundle:Orders:list, page:1 }
    requirements:
        page: \d+

admin_homepage.order_products:
    path:   /order/{id}/products
    defaults: { _controller: AdminBundle:Orders:products }
    requirements:
        id: \d+

admin_homepage.order_resolve:
    path:   /order/{id}/resolve
    defaults: { _controller: AdminBundle:Orders:resolve }
    requirements:
        id: \d+

admin_homepage.order_reject:
    path:   /order/{id}/reject
    defaults: { _controller: AdminBundle:Orders:reject }
    requirements:
        id: \d+