services:
    Admin.checkimg:
        class: AdminBundle\SomeClasses\CheckImg
        arguments:
            - "%uplouad_image_type%"
    Admin.imageNameGen:
            class: AdminBundle\SomeClasses\imageNameGen