<?php

namespace UserBundle\Repository;
use UserBundle\Entity\Customer;
use UserBundle\Entity\CustomerOrder;

/**
 * CustomerOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerOrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOrCreateOrder(Customer $customer)
    {
        $manager = $this->getEntityManager();
        $dql = 'select o from UserBundle:CustomerOrder o where o.customer = :customer and o.status = :status';
        $order = $manager->createQuery($dql)->setParameters([
            'customer' => $customer,
            'status' => CustomerOrder::STATUS_OPEN
        ])->getOneOrNullResult();

        if ($order == null)
        {
            $order = new CustomerOrder();
            $customer->addOrder($order);
            $manager->persist($customer);
            $manager->flush();
        }
        return $order;
    }

}
