<?php

namespace UserBundle\Repository;

/**
 * PhotoCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
