<?php

namespace UserBundle\Repository;

/**
 * PhotoProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoProductRepository extends \Doctrine\ORM\EntityRepository
{
}
